import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    slug: "oleo-oliva-extra-virgem-750ml",
    sku: "ACT-FOO-001",
    ean: "5414315001001",
    price: 3.99,
    originalPrice: 5.49,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 150,
    images: [{ url: "", alt: "Azeite Extra Virgem" }],
    attributes: [
      { name: "Capacity", value: "750ml" },
      { name: "Origin", value: "Grécia" },
    ],
    translations: {
      "pt-PT": { name: "Azeite Extra Virgem 750ml", description: "Azeite de oliva extra virgem de alta qualidade, prensado a frio. Ideal para saladas e cozinhados.", shortDesc: "Azeite premium prensado a frio" },
      "fr-FR": { name: "Huile d'Olive Extra Vierge 750ml", description: "Huile d'olive extra vierge de haute qualité, pressée à froid. Idéale pour les salades et la cuisine.", shortDesc: "Huile d'olive premium pressée à froid" },
      "es-ES": { name: "Aceite de Oliva Extra Virgen 750ml", description: "Aceite de oliva extra virgen de alta calidad, prensado en frío. Ideal para ensaladas y cocinados.", shortDesc: "Aceite premium prensado en frío" },
      "it-IT": { name: "Olio Extra Vergine d'Oliva 750ml", description: "Olio extravergine di oliva di alta qualità, spremuto a freddo. Ideale per insalate e cottura.", shortDesc: "Olio premium spremuto a freddo" },
      "nl-NL": { name: "Extra Vierge Olijfolie 750ml", description: "Extra vierge olijfolie van hoge kwaliteit, koudgeperst. Ideaal voor salades en koken.", shortDesc: "Premium koudgeperste olijfolie" },
      "de-DE": { name: "Natives Olivenöl Extra 750ml", description: "Hochwertiges natives Olivenöl Extra, kaltgepresst. Ideal für Salate und Kochen.", shortDesc: "Premium kaltgepresstes Olivenöl" },
      "fr-BE": { name: "Huile d'Olive Extra Vierge 750ml", description: "Huile d'olive extra vierge, pressée à froid.", shortDesc: "Huile premium pressée à froid" },
      "lb-LU": { name: "Extra Vierge Uelef 750ml", description: "Héchwäerteg extra Vierge Uelef, kalt gepresst.", shortDesc: "Premium kaltgepresst Uelef" },
      "pt-BR": { name: "Azeite de Oliva Extra Virgem 750ml", description: "Azeite de oliva extra virgem de alta qualidade, prensado a frio.", shortDesc: "Azeite premium prensado a frio" },
    },
  },
  {
    id: "prod-002",
    slug: "detergente-roupa-liquido-2l",
    sku: "ACT-CLE-001",
    ean: "5414315001002",
    price: 2.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: false,
    stockCount: 300,
    images: [{ url: "", alt: "Detergente Líquido" }],
    attributes: [
      { name: "Capacity", value: "2L" },
      { name: "Scent", value: "Lavanda" },
    ],
    translations: {
      "pt-PT": { name: "Detergente Líquido 2L", description: "Detergente líquido concentrado para roupa. Perfume suave de lavanda. Para 40 lavagens.", shortDesc: "Detergente concentrado, 40 lavagens" },
      "fr-FR": { name: "Lessive Liquide 2L", description: "Lessive liquide concentrée pour le linge. Parfum doux de lavande. Pour 40 lavages.", shortDesc: "Lessive concentrée, 40 lavages" },
      "es-ES": { name: "Detergente Líquido 2L", description: "Detergente líquido concentrado para la ropa. Suave aroma de lavanda. Para 40 lavados.", shortDesc: "Detergente concentrado, 40 lavados" },
      "it-IT": { name: "Detersivo Liquido 2L", description: "Detersivo liquido concentrato per bucato. Profumo delicato di lavanda. Per 40 lavaggi.", shortDesc: "Detersivo concentrato, 40 lavaggi" },
      "nl-NL": { name: "Vloeibaar Wasmiddel 2L", description: "Geconcentreerd vloeibaar wasmiddel. Zachte lavendelgeur. Voor 40 wasbeurten.", shortDesc: "Geconcentreerd wasmiddel, 40 wasbeurten" },
      "de-DE": { name: "Flüssigwaschmittel 2L", description: "Konzentriertes Flüssigwaschmittel. Sanfter Lavendelduft. Für 40 Wäschen.", shortDesc: "Konzentriertes Waschmittel, 40 Wäschen" },
      "fr-BE": { name: "Lessive Liquide 2L", description: "Lessive liquide concentrée pour le linge.", shortDesc: "Lessive concentrée" },
      "lb-LU": { name: "Flësseg Wäschmëttel 2L", description: "Konzentréiert flësseg Wäschmëttel. Milt Lavendelduft.", shortDesc: "Konzentréiert Wäschmëttel" },
      "pt-BR": { name: "Detergente Líquido 2L", description: "Detergente líquido concentrado para roupas. Aroma suave de lavanda.", shortDesc: "Detergente concentrado, 40 lavagens" },
    },
  },
  {
    id: "prod-003",
    slug: "kit-ferramentas-basico-45-pecas",
    sku: "ACT-BRI-001",
    ean: "5414315001003",
    price: 9.99,
    originalPrice: 14.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 75,
    images: [{ url: "", alt: "Kit de Ferramentas" }],
    attributes: [
      { name: "Pieces", value: "45" },
      { name: "Material", value: "Aço Carbono" },
    ],
    translations: {
      "pt-PT": { name: "Kit Ferramentas 45 Peças", description: "Kit completo de ferramentas com 45 peças. Inclui chaves, martelo, alicate e mais.", shortDesc: "Kit completo para bricolage" },
      "fr-FR": { name: "Outil de Bricolage 45 Pièces", description: "Kit complet d'outils avec 45 pièces. Inclut clés, marteau, pince et plus.", shortDesc: "Kit complet pour bricolage" },
      "es-ES": { name: "Kit de Herramientas 45 Piezas", description: "Kit completo de herramientas con 45 piezas. Incluye llaves, martillo, alicate y más.", shortDesc: "Kit completo para bricolaje" },
      "it-IT": { name: "Kit Utensili 45 Pezzi", description: "Kit completo di utensili con 45 pezzi. Include chiavi, martello, pinza e altro.", shortDesc: "Kit completo per fai da te" },
      "nl-NL": { name: "Gereedschapskist 45 Stuks", description: "Complete gereedschapsset met 45 stuks. Inclusief sleutels, hamer, tang en meer.", shortDesc: "Complete klusset" },
      "de-DE": { name: "Werkzeugkasten 45 Teile", description: "Komplettes Werkzeugset mit 45 Teilen. Enthält Schlüssel, Hammer, Zange und mehr.", shortDesc: "Komplettes Werkzeugset" },
      "fr-BE": { name: "Kit Outils 45 Pièces", description: "Kit complet d'outils avec 45 pièces.", shortDesc: "Kit complet pour bricolage" },
      "lb-LU": { name: "Geschirskasten 45 Stéck", description: "Kompletten Handwierkssatz mat 45 Stéck.", shortDesc: "Kompletten Handwierkssatz" },
      "pt-BR": { name: "Kit de Ferramentas 45 Peças", description: "Kit completo de ferramentas com 45 peças para bricolage.", shortDesc: "Kit completo para bricolage" },
    },
  },
  {
    id: "prod-004",
    slug: "conjunto-toalhas-banho-3-pocos",
    sku: "ACT-HOM-001",
    ean: "5414315001004",
    price: 7.99,
    originalPrice: 12.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 60,
    images: [{ url: "", alt: "Conjunto de Toalhas" }],
    attributes: [
      { name: "Pieces", value: "3" },
      { name: "Material", value: "Algodão 100%" },
    ],
    translations: {
      "pt-PT": { name: "Conjunto Toalhas Banho 3 Peças", description: "Conjunto de toalhas de banho em algodão premium. Inclui 2 toalhas de rosto e 1 de banho.", shortDesc: "Toalhas de algodão premium" },
      "fr-FR": { name: "Ensemble Serviettes 3 Pièces", description: "Ensemble de serviettes de bain en coton premium. Inclus 2 serviettes de visage et 1 de bain.", shortDesc: "Serviettes en coton premium" },
      "es-ES": { name: "Juego de Toallas 3 Piezas", description: "Juego de toallas de baño en algodón premium. Incluye 2 toallas de rostro y 1 de baño.", shortDesc: "Toallas de algodón premium" },
      "it-IT": { name: "Set Asciugamani 3 Pezzi", description: "Set di asciugamani da bagno in cotone premium. Include 2 asciugamani viso e 1 da bagno.", shortDesc: "Asciugamani in cotone premium" },
      "nl-NL": { name: "Handdoekenset 3 Stuks", description: "Badhanddoekenset in premium katoen. Inclusief 2 washandjes en 1 badhanddoek.", shortDesc: "Premium katoenen handdoeken" },
      "de-DE": { name: "Handtuchset 3 Teile", description: "Badhandtuchset aus Premium-Baumwolle. Enthält 2 Waschlappen und 1 Badetuch.", shortDesc: "Premium Baumwollhandtücher" },
      "fr-BE": { name: "Ensemble Serviettes 3 Pièces", description: "Ensemble de serviettes de bain en coton premium.", shortDesc: "Serviettes en coton premium" },
      "lb-LU": { name: "Handuchenset 3 Stéck", description: "Badhanduchenset aus Premium-Bamwull.", shortDesc: "Premium Bamwullhandducher" },
      "pt-BR": { name: "Jogo de Toalhas 3 Peças", description: "Jogo de toalhas de banho em algodão premium.", shortDesc: "Toalhas de algodão premium" },
    },
  },
  {
    id: "prod-005",
    slug: "fertilizante-universal-5kg",
    sku: "ACT-GAR-001",
    ean: "5414315001005",
    price: 4.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 200,
    images: [{ url: "", alt: "Fertilizante" }],
    attributes: [
      { name: "Weight", value: "5kg" },
      { name: "Type", value: "Universal" },
    ],
    translations: {
      "pt-PT": { name: "Fertilizante Universal 5kg", description: "Fertilizante universal para todas as plantas. Fórmula equilibrada NPK para crescimento saudável.", shortDesc: "Para todas as plantas" },
      "fr-FR": { name: "Engrais Universel 5kg", description: "Engrais universel pour toutes les plantes. Formule équilibrée NPK pour une croissance saine.", shortDesc: "Pour toutes les plantes" },
      "es-ES": { name: "Fertilizante Universal 5kg", description: "Fertilizante universal para todas las plantas. Fórmula equilibrada NPK.", shortDesc: "Para todas las plantas" },
      "it-IT": { name: "Concime Universale 5kg", description: "Concime universale per tutte le piante. Formula bilanciata NPK.", shortDesc: "Per tutte le piante" },
      "nl-NL": { name: "Universele Meststof 5kg", description: "Universele meststof voor alle planten. Gebalanceerde NPK-formule.", shortDesc: "Voor alle planten" },
      "de-DE": { name: "Universaldünger 5kg", description: "Universaldünger für alle Pflanzen. Ausgewogene NPK-Formel.", shortDesc: "Für alle Pflanzen" },
      "fr-BE": { name: "Engrais Universel 5kg", description: "Engrais universel pour toutes les plantes.", shortDesc: "Pour toutes les plantes" },
      "lb-LU": { name: "Universaldünger 5kg", description: "Universaldünger fir all Planzen.", shortDesc: "Fir all Planzen" },
      "pt-BR": { name: "Fertilizante Universal 5kg", description: "Fertilizante universal para todas as plantas.", shortDesc: "Para todas as plantas" },
    },
  },
  {
    id: "prod-006",
    slug: "racao-cao-adulto-3kg",
    sku: "ACT-PET-001",
    ean: "5414315001006",
    price: 6.99,
    originalPrice: 8.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 120,
    images: [{ url: "", alt: "Ração para Cão" }],
    attributes: [
      { name: "Weight", value: "3kg" },
      { name: "Animal", value: "Cão Adulto" },
    ],
    translations: {
      "pt-PT": { name: "Ração Cão Adulto 3kg", description: "Ração completa e equilibrada para cães adultos. Com frango e legumes.", shortDesc: "Ração premium para cães" },
      "fr-FR": { name: "Aliment Chien Adulte 3kg", description: "Aliment complet et équilibré pour chiens adultes. Avec poulet et légumes.", shortDesc: "Aliment premium pour chiens" },
      "es-ES": { name: "Comida Perro Adulto 3kg", description: "Comida completa y equilibrada para perros adultos. Con pollo y verduras.", shortDesc: "Comida premium para perros" },
      "it-IT": { name: "Cibo Cane Adulto 3kg", description: "Cibo completo e bilanciato per cani adulti. Con pollo e verdure.", shortDesc: "Cibo premium per cani" },
      "nl-NL": { name: "Hondenvoer Volwassen 3kg", description: "Compleet en uitgebalanceerd hondenvoer voor volwassen honden. Met kip en groenten.", shortDesc: "Premium hondenvoer" },
      "de-DE": { name: "Hundefutter Erwachsen 3kg", description: "Vollwertiges und ausgewogenes Hundefutter für erwachsene Hunde. Mit Huhn und Gemüse.", shortDesc: "Premium Hundefutter" },
      "fr-BE": { name: "Aliment Chien Adulte 3kg", description: "Aliment complet pour chiens adultes.", shortDesc: "Aliment premium pour chiens" },
      "lb-LU": { name: "Hondsfriessen Erwuessen 3kg", description: "Kompletten Hondsfriessen fir erwuessen Honden.", shortDesc: "Premium Hondsfriessen" },
      "pt-BR": { name: "Ração Cão Adulto 3kg", description: "Ração completa para cães adultos. Com frango e legumes.", shortDesc: "Ração premium para cães" },
    },
  },
  {
    id: "prod-007",
    slug: "shampoo-solido-argan-85g",
    sku: "ACT-HYG-001",
    ean: "5414315001007",
    price: 1.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 500,
    images: [{ url: "", alt: "Shampoo Sólido" }],
    attributes: [
      { name: "Weight", value: "85g" },
      { name: "Ingredient", value: "Óleo de Argan" },
    ],
    translations: {
      "pt-PT": { name: "Shampoo Sólido Argan 85g", description: "Shampoo sólido com óleo de argan. Zero plástico, 100% natural. Equivalente a 2 frascos.", shortDesc: "Shampoo zero plástico" },
      "fr-FR": { name: "Shampoo Solide Argan 85g", description: "Shampoo solide à l'huile d'argan. Zéro plastique, 100% naturel. Équivalent à 2 flacons.", shortDesc: "Shampoo zéro plastique" },
      "es-ES": { name: "Champú Sólido Argán 85g", description: "Champú sólido con aceite de argán. Cero plástico, 100% natural. Equivalente a 2 frascos.", shortDesc: "Champú cero plástico" },
      "it-IT": { name: "Shampoo Solido Argan 85g", description: "Shampoo solido con olio di argan. Zero plastica, 100% naturale. Equivalente a 2 flaconi.", shortDesc: "Shampoo zero plastica" },
      "nl-NL": { name: "Vast Shampoo Argan 85g", description: "Vast shampoo met arganolie. Zero plastic, 100% natuurlijk. Gelijk aan 2 flessen.", shortDesc: "Shampoo zero plastic" },
      "de-DE": { name: "Festshampoo Argan 85g", description: "Festshampoo mit Arganöl. Null Plastik, 100% natürlich. Entspricht 2 Flaschen.", shortDesc: "Shampoo null Plastik" },
      "fr-BE": { name: "Shampoo Solide Argan 85g", description: "Shampoo solide à l'huile d'argan. Zéro plastique.", shortDesc: "Shampoo zéro plastique" },
      "lb-LU": { name: "Festshampoo Argan 85g", description: "Festshampoo mat Arganuele. Null Plastik.", shortDesc: "Shampoo null Plastik" },
      "pt-BR": { name: "Shampoo Sólido Argan 85g", description: "Shampoo sólido com óleo de argan. Zero plástico, 100% natural.", shortDesc: "Shampoo zero plástico" },
    },
  },
  {
    id: "prod-008",
    slug: "kit-escolar-completo-12-pocos",
    sku: "ACT-OFF-001",
    ean: "5414315001008",
    price: 5.99,
    originalPrice: 8.99,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: true,
    stockCount: 180,
    images: [{ url: "", alt: "Kit Escolar" }],
    attributes: [
      { name: "Pieces", value: "12" },
      { name: "Type", value: "Material Escolar" },
    ],
    translations: {
      "pt-PT": { name: "Kit Escolar 12 Peças", description: "Kit escolar completo com canetas, lápis, borracha, régua e caderno. Tudo num estojo.", shortDesc: "Tudo para voltar às aulas" },
      "fr-FR": { name: "Kit Scolaire 12 Pièces", description: "Kit scolaire complet avec stylos, crayons, gomme, règle et cahier. Tout dans une trousse.", shortDesc: "Tout pour la rentrée" },
      "es-ES": { name: "Kit Escolar 12 Piezas", description: "Kit escolar completo con bolígrafos, lápices, goma, regla y cuaderno.", shortDesc: "Todo para la vuelta al cole" },
      "it-IT": { name: "Kit Scolastico 12 Pezzi", description: "Kit scolastico completo con penne, matite, gomma, righello e quaderno.", shortDesc: "Tutto per la scuola" },
      "nl-NL": { name: "Schoolset 12 Stuks", description: "Complete schoolset met pennen, potloden, gum, liniaal en schrift.", shortDesc: "Alles voor school" },
      "de-DE": { name: "Schulset 12 Teile", description: "Komplettes Schulset mit Stiften, Bleistiften, Radiergummi, Lineal und Heft.", shortDesc: "Alles für die Schule" },
      "fr-BE": { name: "Kit Scolaire 12 Pièces", description: "Kit scolaire complet.", shortDesc: "Tout pour la rentrée" },
      "lb-LU": { name: "Schoulset 12 Stéck", description: "Kompletten Schoulset.", shortDesc: "Alles fir d'Schoul" },
      "pt-BR": { name: "Kit Escolar 12 Peças", description: "Kit escolar completo com canetas, lápis e mais.", shortDesc: "Tudo para voltar às aulas" },
    },
  },
  {
    id: "prod-009",
    slug: "puzzle-1000-pocos-paisagem",
    sku: "ACT-TOY-001",
    ean: "5414315001009",
    price: 3.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 90,
    images: [{ url: "", alt: "Puzzle 1000 Peças" }],
    attributes: [
      { name: "Pieces", value: "1000" },
      { name: "Theme", value: "Paisagem" },
    ],
    translations: {
      "pt-PT": { name: "Puzzle 1000 Peças - Paisagem", description: "Puzzle de 1000 peças com paisagem europeia. Impressão de alta qualidade em cartão grosso.", shortDesc: "Puzzle para toda a família" },
      "fr-FR": { name: "Puzzle 1000 Pièces - Paysage", description: "Puzzle de 1000 pièces avec paysage européen. Impression haute qualité sur carton épais.", shortDesc: "Puzzle pour toute la famille" },
      "es-ES": { name: "Puzzle 1000 Piezas - Paisaje", description: "Puzzle de 1000 piezas con paisaje europeo. Impresión de alta calidad.", shortDesc: "Puzzle para toda la familia" },
      "it-IT": { name: "Puzzle 1000 Pezzi - Paesaggio", description: "Puzzle di 1000 pezzi con paesaggio europeo. Stampa di alta qualità.", shortDesc: "Puzzle per tutta la famiglia" },
      "nl-NL": { name: "Puzzle 1000 Stuks - Landschap", description: "Puzzle van 1000 stuks met Europees landschap. Hoge kwaliteit druk op dik karton.", shortDesc: "Puzzle voor het hele gezin" },
      "de-DE": { name: "Puzzle 1000 Teile - Landschaft", description: "Puzzle mit 1000 Teilen, europäisches Landschaftsmotiv. Hochwertiger Druck auf starkem Karton.", shortDesc: "Puzzle für die ganze Familie" },
      "fr-BE": { name: "Puzzle 1000 Pièces - Paysage", description: "Puzzle de 1000 pièces avec paysage.", shortDesc: "Puzzle pour toute la famille" },
      "lb-LU": { name: "Puzzle 1000 Stéck - Landschaft", description: "Puzzle mat 1000 Stéck, europäescht Landschaftsmotiv.", shortDesc: "Puzzle fir déi ganz Famill" },
      "pt-BR": { name: "Quebra-cabeça 1000 Peças - Paisagem", description: "Quebra-cabeça de 1000 peças com paisagem europeia.", shortDesc: "Quebra-cabeça para toda a família" },
    },
  },
  {
    id: "prod-010",
    slug: "camisola-algodao-unissex",
    sku: "ACT-CLT-001",
    ean: "5414315001010",
    price: 4.99,
    originalPrice: 7.99,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: true,
    stockCount: 250,
    images: [{ url: "", alt: "Camisola de Algodão" }],
    attributes: [
      { name: "Material", value: "Algodão 100%" },
      { name: "Sizes", value: "S, M, L, XL, XXL" },
    ],
    translations: {
      "pt-PT": { name: "Camisola Algodão Unissex", description: "Camisola de algodão 100% confortável. Corte regular, ideal para o dia a dia.", shortDesc: "Confortável algodão premium" },
      "fr-FR": { name: "T-shirt Coton Unisexe", description: "T-shirt 100% coton confortable. Coupe régulière, idéal pour tous les jours.", shortDesc: "Coton premium confortable" },
      "es-ES": { name: "Camiseta Algodón Unisex", description: "Camiseta de algodón 100% cómoda. Corte regular, ideal para el día a día.", shortDesc: "Algodón premium cómodo" },
      "it-IT": { name: "T-shirt Cotone Unisex", description: "T-shirt 100% cotone confortevole. Taglio regolare, ideale per tutti i giorni.", shortDesc: "Cotone premium confortevole" },
      "nl-NL": { name: "T-shirt Katoen Unisex", description: "Comfortabel T-shirt 100% katoen. Reguliere pasvorm, ideaal voor alledag.", shortDesc: "Premium katoen comfortabel" },
      "de-DE": { name: "Baumwoll-T-Shirt Unisex", description: "Bequemes 100% Baumwoll-T-Shirt. Reguläre Passform, ideal für jeden Tag.", shortDesc: "Premium Baumwolle bequem" },
      "fr-BE": { name: "T-shirt Coton Unisexe", description: "T-shirt 100% coton confortable.", shortDesc: "Coton premium confortable" },
      "lb-LU": { name: "Bamwoll T-Shirt Unisex", description: "Bequemt 100% Bamwoll T-Shirt.", shortDesc: "Premium Bamwoll bequem" },
      "pt-BR": { name: "Camiseta Algodão Unissex", description: "Camiseta de algodão 100% confortável.", shortDesc: "Algodão premium confortável" },
    },
  },
  {
    id: "prod-011",
    slug: "velas-aromaticas-set-6",
    sku: "ACT-DEC-001",
    ean: "5414315001011",
    price: 2.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: true,
    isNew: true,
    isOnSale: false,
    stockCount: 350,
    images: [{ url: "", alt: "Velas Aromáticas" }],
    attributes: [
      { name: "Pieces", value: "6" },
      { name: "Burn Time", value: "4h cada" },
    ],
    translations: {
      "pt-PT": { name: "Velas Aromáticas Set 6", description: "Conjunto de 6 velas aromáticas com aromas de lavanda, baunilha e cítricos. Tempo de queima: 4h cada.", shortDesc: "Ambiente acolhedor" },
      "fr-FR": { name: "Bougies Parfumées Set 6", description: "Ensemble de 6 bougies parfumées aux arômes de lavande, vanille et agrumes. Temps de combustion: 4h chacune.", shortDesc: "Ambiance chaleureuse" },
      "es-ES": { name: "Velas Aromáticas Set 6", description: "Juego de 6 velas aromáticas con aromas de lavanda, vainilla y cítricos. Tiempo de combustión: 4h cada.", shortDesc: "Ambiente acogedor" },
      "it-IT": { name: "Candele Profumate Set 6", description: "Set di 6 candele profumate con aromi di lavanda, vaniglia e agrumi. Tempo di combustione: 4h ciascuna.", shortDesc: "Atmosfera accogliente" },
      "nl-NL": { name: "Geurkaarsen Set 6", description: "Set van 6 geurkaarsen met lavendel-, vanille- en citroenaroma's. Brandtijd: 4 uur per kaars.", shortDesc: "Gezellige sfeer" },
      "de-DE": { name: "Duftkerzen Set 6", description: "Set mit 6 Duftkerzen in Lavendel-, Vanille- und Zitrusdüften. Brenndauer: 4h pro Kerze.", shortDesc: "Gemütliche Atmosphäre" },
      "fr-BE": { name: "Bougies Parfumées Set 6", description: "Ensemble de 6 bougies parfumées.", shortDesc: "Ambiance chaleureuse" },
      "lb-LU": { name: "Duftrausen Set 6", description: "Set mat 6 Duftrausen.", shortDesc: "Gemittlech Atmosphär" },
      "pt-BR": { name: "Velas Aromáticas Set 6", description: "Conjunto de 6 velas aromáticas.", shortDesc: "Ambiente acolhedor" },
    },
  },
  {
    id: "prod-012",
    slug: "conjunto-talheres-24-pocos",
    sku: "ACT-KIT-001",
    ean: "5414315001012",
    price: 8.99,
    originalPrice: 12.49,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: true,
    stockCount: 80,
    images: [{ url: "", alt: "Conjunto de Talheres" }],
    attributes: [
      { name: "Pieces", value: "24" },
      { name: "Material", value: "Aço Inox 18/10" },
    ],
    translations: {
      "pt-PT": { name: "Talheres Aço Inox 24 Peças", description: "Conjunto de talheres em aço inoxidável 18/10. Serve 6 pessoas. Design moderno.", shortDesc: "Aço inoxidável premium" },
      "fr-FR": { name: "Coutellerie Acier Inoxydable 24 Pièces", description: "Ensemble de couverts en acier inoxydable 18/10. Pour 6 personnes. Design moderne.", shortDesc: "Acier inoxydable premium" },
      "es-ES": { name: "Cubertería Acero Inox 24 Piezas", description: "Juego de cubiertos en acero inoxidable 18/10. Para 6 personas. Diseño moderno.", shortDesc: "Acero inoxidable premium" },
      "it-IT": { name: "Posate Acciaio Inox 24 Pezzi", description: "Set di posate in acciaio inox 18/10. Per 6 persone. Design moderno.", shortDesc: "Acciaio inox premium" },
      "nl-NL": { name: "Bestekset Roestvrij Staal 24 Stuks", description: "Bestekset in roestvrij staal 18/10. Voor 6 personen. Modern design.", shortDesc: "Premium roestvrij staal" },
      "de-DE": { name: "Besteckset Edelstahl 24 Teile", description: "Besteckset aus Edelstahl 18/10. Für 6 Personen. Modernes Design.", shortDesc: "Premium Edelstahl" },
      "fr-BE": { name: "Coutellerie Acier 24 Pièces", description: "Ensemble de couverts en acier inoxydable.", shortDesc: "Acier inoxydable premium" },
      "lb-LU": { name: "Bestéckset Edelstahl 24 Stéck", description: "Bestéckset aus Edelstahl.", shortDesc: "Premium Edelstahl" },
      "pt-BR": { name: "Conjunto de Talheres 24 Peças", description: "Conjunto de talheres em aço inoxidável 18/10.", shortDesc: "Aço inoxidável premium" },
    },
  },
  {
    id: "prod-013",
    slug: "martelo-carpinteiro-300g",
    sku: "ACT-BRI-002",
    ean: "5414315001013",
    price: 3.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 200,
    images: [{ url: "", alt: "Martelo de Carpinteiro" }],
    attributes: [
      { name: "Weight", value: "300g" },
      { name: "Material", value: "Aço + Fibra de Vidro" },
    ],
    translations: {
      "pt-PT": { name: "Martelo Carpinteiro 300g", description: "Martelo profissional com cabo em fibra de vidro e cabeça em aço. Ergonómico e resistente.", shortDesc: "Martelo profissional" },
      "fr-FR": { name: "Marteau Charpentier 300g", description: "Marteau professionnel avec manche en fibre de verre et tête en acier. Ergonomique et résistant.", shortDesc: "Marteau professionnel" },
      "es-ES": { name: "Martillo Carpintero 300g", description: "Martillo profesional con mango de fibra de vidro y cabeza de acero. Ergonómico y resistente.", shortDesc: "Martillo profesional" },
      "it-IT": { name: "Martello Falegname 300g", description: "Martello professionale con manico in fibra di vetro e testa in acciaio. Ergonomico e resistente.", shortDesc: "Martello professionale" },
      "nl-NL": { name: "Hamer Timmerman 300g", description: "Professionele hamer met glasvezel handgreep en stalen kop. Ergonomisch en duurzaam.", shortDesc: "Professionele hamer" },
      "de-DE": { name: "Zimmermannshammer 300g", description: "Professioneller Hammer mit Glasfaserstiel und Stahlkopf. Ergonomisch und robust.", shortDesc: "Professioneller Hammer" },
      "fr-BE": { name: "Marteau Charpentier 300g", description: "Marteau professionnel avec manche en fibre de verre.", shortDesc: "Marteau professionnel" },
      "lb-LU": { name: "Zimmermannshammer 300g", description: "Professionellen Hammer mat Glasfaserstiel.", shortDesc: "Professionellen Hammer" },
      "pt-BR": { name: "Martelo Carpinteiro 300g", description: "Martelo profissional com cabo de fibra de vidro.", shortDesc: "Martelo profissional" },
    },
  },
  {
    id: "prod-014",
    slug: "organizador-gavetas-3-gavetas",
    sku: "ACT-ORG-001",
    ean: "5414315001014",
    price: 5.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 110,
    images: [{ url: "", alt: "Organizador de Gavetas" }],
    attributes: [
      { name: "Drawers", value: "3" },
      { name: "Material", value: "Plástico" },
    ],
    translations: {
      "pt-PT": { name: "Organizador 3 Gavetas", description: "Organizador com 3 gavetas transparentes. Ideal para escritório, casa de banho ou cozinha.", shortDesc: "Organize seu espaço" },
      "fr-FR": { name: "Organiseur 3 Tiroirs", description: "Organiseur avec 3 tiroirs transparents. Idéal pour bureau, salle de bain ou cuisine.", shortDesc: "Organisez votre espace" },
      "es-ES": { name: "Organizador 3 Cajones", description: "Organizador con 3 cajones transparentes. Ideal para oficina, baño o cocina.", shortDesc: "Organice su espacio" },
      "it-IT": { name: "Organizer 3 Cassetti", description: "Organizer con 3 cassetti trasparenti. Ideale per ufficio, bagno o cucina.", shortDesc: "Organizza il tuo spazio" },
      "nl-NL": { name: "Organizer 3 Lades", description: "Organizer met 3 transparante lades. Ideaal voor kantoor, badkamer of keuken.", shortDesc: "Organiseer uw ruimte" },
      "de-DE": { name: "Organizer 3 Schubladen", description: "Organizer mit 3 transparenten Schubladen. Ideal für Büro, Bad oder Küche.", shortDesc: "Organisieren Sie Ihren Raum" },
      "fr-BE": { name: "Organiseur 3 Tiroirs", description: "Organiseur avec 3 tiroirs transparents.", shortDesc: "Organisez votre espace" },
      "lb-LU": { name: "Organisateur 3 Schubladen", description: "Organisateur mat 3 transparent Schubladen.", shortDesc: "Organiséiert Äre Raum" },
      "pt-BR": { name: "Organizador 3 Gavetas", description: "Organizador com 3 gavetas transparentes.", shortDesc: "Organize seu espaço" },
    },
  },
  {
    id: "prod-015",
    slug: "sacos-lixo-30-unidades",
    sku: "ACT-CLE-002",
    ean: "5414315001015",
    price: 1.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 1000,
    images: [{ url: "", alt: "Sacos de Lixo" }],
    attributes: [
      { name: "Quantity", value: "30 unidades" },
      { name: "Capacity", value: "50L" },
    ],
    translations: {
      "pt-PT": { name: "Sacos de Lixo 50L 30uds", description: "Sacos de lixo resistentes de 50 litros. Pacote com 30 unidades. Fechamento seguro.", shortDesc: "Resistentes e práticos" },
      "fr-FR": { name: "Sacs Poubelle 50L 30 pcs", description: "Sacs poubelle résistants de 50 litres. Paquet de 30 unités. Fermeture sécurisée.", shortDesc: "Résistants et pratiques" },
      "es-ES": { name: "Bolsas Basura 50L 30uds", description: "Bolsas de basura resistentes de 50 litros. Paquete con 30 unidades.", shortDesc: "Resistentes y prácticos" },
      "it-IT": { name: "Sacchi Immondizia 50L 30pz", description: "Sacchi della spazzatura resistenti da 50 litri. Confezione da 30 pezzi.", shortDesc: "Resistenti e pratici" },
      "nl-NL": { name: "Vuilniszakken 50L 30 stuks", description: "Sterke vuilniszakken van 50 liter. Verpakking met 30 stuks.", shortDesc: "Sterk en praktisch" },
      "de-DE": { name: "Müllbeutel 50L 30 Stück", description: "Robuste Müllbeutel à 50 Liter. Packung mit 30 Stück.", shortDesc: "Robust und praktisch" },
      "fr-BE": { name: "Sacs Poubelle 50L 30 pcs", description: "Sacs poubelle résistants de 50 litres.", shortDesc: "Résistants et pratiques" },
      "lb-LU": { name: "Müllbeutel 50L 30 Stéck", description: "Robust Müllbeutel 50 Liter.", shortDesc: "Robust a praktesch" },
      "pt-BR": { name: "Sacos de Lixo 50L 30un", description: "Sacos de lixo resistentes de 50 litros. Pacote com 30 unidades.", shortDesc: "Resistentes e práticos" },
    },
  },
  {
    id: "prod-016",
    slug: "suco-laranja-natural-1l",
    sku: "ACT-FOO-002",
    ean: "5414315001016",
    price: 1.29,
    originalPrice: 1.79,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 400,
    images: [{ url: "", alt: "Sumo de Laranja" }],
    attributes: [
      { name: "Capacity", value: "1L" },
      { name: "Type", value: "100% Sumo Natural" },
    ],
    translations: {
      "pt-PT": { name: "Sumo de Laranja Natural 1L", description: "Sumo de laranja 100% natural, sem adição de açúcar. Fonte de vitamina C.", shortDesc: "100% natural, sem açúcar" },
      "fr-FR": { name: "Jus d'Orange Naturel 1L", description: "Jus d'orange 100% naturel, sans sucre ajouté. Source de vitamine C.", shortDesc: "100% naturel, sans sucre" },
      "es-ES": { name: "Zumo de Naranja Natural 1L", description: "Zumo de naranja 100% natural, sin azúcar añadido. Fuente de vitamina C.", shortDesc: "100% natural, sin azúcar" },
      "it-IT": { name: "Succo d'Arancia Naturale 1L", description: "Succo d'arancia 100% naturale, senza zuccheri aggiunti. Fonte di vitamina C.", shortDesc: "100% naturale, senza zuccheri" },
      "nl-NL": { name: "Natuurlijk Sinaasappelsap 1L", description: "100% natuurlijk sinaasappelsap, zonder toegevoegde suiker. Bron van vitamine C.", shortDesc: "100% natuurlijk, zonder suiker" },
      "de-DE": { name: "Natürlicher Orangensaft 1L", description: "100% natürlicher Orangensaft, ohne Zuckerzusatz. Quelle von Vitamin C.", shortDesc: "100% natürlich, ohne Zucker" },
      "fr-BE": { name: "Jus d'Orange Naturel 1L", description: "Jus d'orange 100% naturel, sans sucre ajouté.", shortDesc: "100% naturel, sans sucre" },
      "lb-LU": { name: "Natierlechen Orangesaft 1L", description: "100% natierlechen Orangesaft, ouni Zukker.", shortDesc: "100% natierlech" },
      "pt-BR": { name: "Suco de Laranja Natural 1L", description: "Suco de laranja 100% natural, sem açúcar adicionado.", shortDesc: "100% natural, sem açúcar" },
    },
  },
  {
    id: "prod-017",
    slug: "lamp-led-banco-5w",
    sku: "ACT-LGT-001",
    ean: "5414315001017",
    price: 6.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 150,
    images: [{ url: "", alt: "Lâmpada LED" }],
    attributes: [
      { name: "Power", value: "5W" },
      { name: "Equivalent", value: "40W incandescente" },
    ],
    translations: {
      "pt-PT": { name: "Lâmpada LED Banco 5W", description: "Lâmpada LED de banco com braço articulável e dimmer. Luz quente regulável.", shortDesc: "Luz ajustável e elegante" },
      "fr-FR": { name: "Lampe LED Bureau 5W", description: "Lampe LED de bureau avec bras articulé et variateur. Lumière chaude réglable.", shortDesc: "Lumière réglable et élégante" },
      "es-ES": { name: "Lámpara LED Escritorio 5W", description: "Lámpara LED de escritorio con brazo articulado y regulador. Luz cálida regulable.", shortDesc: "Luz ajustable y elegante" },
      "it-IT": { name: "Lampada LED Scrivania 5W", description: "Lampada LED da scrivania con braccio articolato e dimmer. Luce calda regolabile.", shortDesc: "Luce regolabile ed elegante" },
      "nl-NL": { name: "LED Bureaulamp 5W", description: "LED bureaulamp met draaibaar arm en dimmer. Verstelbaar warm licht.", shortDesc: "Instelbaar en elegant licht" },
      "de-DE": { name: "LED Schreibtischlampe 5W", description: "LED Schreibtischlampe mit schwenkbarem Arm und Dimmer. Einstellbares warmes Licht.", shortDesc: "Einstellbares und elegantes Licht" },
      "fr-BE": { name: "Lampe LED Bureau 5W", description: "Lampe LED de bureau avec bras articulé.", shortDesc: "Lumière réglable" },
      "lb-LU": { name: "LED Schreiftdischlampe 5W", description: "LED Schreiftdischlampe mat Schwenkarm.", shortDesc: "Astellbaart Liicht" },
      "pt-BR": { name: "Lâmpada LED Escritório 5W", description: "Lâmpada LED de escritório com braço articulável e dimmer.", shortDesc: "Luz ajustável e elegante" },
    },
  },
  {
    id: "prod-018",
    slug: "almofada-decorativa-45x45",
    sku: "ACT-DEC-002",
    ean: "5414315001018",
    price: 3.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 180,
    images: [{ url: "", alt: "Almofada Decorativa" }],
    attributes: [
      { name: "Size", value: "45x45cm" },
      { name: "Material", value: "Poliéester/Microfibra" },
    ],
    translations: {
      "pt-PT": { name: "Almofada Decorativa 45x45cm", description: "Almofada decorativa com padrão geométrico. Inclui enchimento. Tecido macio e durável.", shortDesc: "Estilo e conforto" },
      "fr-FR": { name: "Coussin Décoratif 45x45cm", description: "Coussin décoratif avec motif géométrique. Inclut le rembourrage. Tissu doux et durable.", shortDesc: "Style et confort" },
      "es-ES": { name: "Cojín Decorativo 45x45cm", description: "Cojín decorativo con patrón geométrico. Incluye relleno. Tela suave y duradera.", shortDesc: "Estilo y confort" },
      "it-IT": { name: "Cuscino Decorativo 45x45cm", description: "Cuscino decorativo con motivo geometrico. Include imbottitura. Tessuto morbido e resistente.", shortDesc: "Stile e comfort" },
      "nl-NL": { name: "Decoratief Kussen 45x45cm", description: "Decoratief kussen met geometrisch patroon. Inclusief vulling. Zacht en duurzaam weefsel.", shortDesc: "Stijl en comfort" },
      "de-DE": { name: "Dekokissen 45x45cm", description: "Dekokissen mit geometrischem Muster. Inklusive Füllung. Weiches und strapazierfähiges Gewebe.", shortDesc: "Stil und Komfort" },
      "fr-BE": { name: "Coussin Décoratif 45x45cm", description: "Coussin décoratif avec motif géométrique.", shortDesc: "Style et confort" },
      "lb-LU": { name: "Dekokissen 45x45cm", description: "Dekokissen mat geometreschem Muster.", shortDesc: "Stil a Komfort" },
      "pt-BR": { name: "Almofada Decorativa 45x45cm", description: "Almofada decorativa com padrão geométrico. Inclui enchimento.", shortDesc: "Estilo e conforto" },
    },
  },
  {
    id: "prod-019",
    slug: "tinta-parede-branco-2-5l",
    sku: "ACT-PNT-001",
    ean: "5414315001019",
    price: 4.99,
    originalPrice: 7.49,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: true,
    stockCount: 95,
    images: [{ url: "", alt: "Tinta para Parede" }],
    attributes: [
      { name: "Capacity", value: "2.5L" },
      { name: "Coverage", value: "~25m²" },
    ],
    translations: {
      "pt-PT": { name: "Tinta Parede Branco 2.5L", description: "Tinta látex para paredes e tetos. Cor branca. Cobertura de aproximadamente 25m² por embalagem.", shortDesc: "Alta cobertura, fácil aplicação" },
      "fr-FR": { name: "Peinture Mur Blanc 2.5L", description: "Peinture latex pour murs et plafonds. Couleur blanche. Couverture d'environ 25m² par pot.", shortDesc: "Haute couverture, application facile" },
      "es-ES": { name: "Pintura Pared Blanco 2.5L", description: "Pintura látex para paredes y techos. Color blanco. Cobertura de aproximadamente 25m².", shortDesc: "Alta cobertura, fácil aplicación" },
      "it-IT": { name: "Vernice Parete Bianco 2.5L", description: "Vernice lattice per pareti e soffitti. Colore bianco. Copertura di circa 25m².", shortDesc: "Alta copertura, facile applicazione" },
      "nl-NL": { name: "Muurverf Wit 2.5L", description: "Latexverf voor muren en plafonds. Witte kleur. Dekking van ongeveer 25m².", shortDesc: "Hoge dekking, gemakkelijk aan te brengen" },
      "de-DE": { name: "Wandfarbe Weiß 2.5L", description: "Latexfarbe für Wände und Decken. Weiße Farbe. Reichweite ca. 25m².", shortDesc: "Hohe Deckkraft, leicht aufzutragen" },
      "fr-BE": { name: "Peinture Mur Blanc 2.5L", description: "Peinture latex pour murs et plafonds.", shortDesc: "Haute couverture" },
      "lb-LU": { name: "Mauerefaarf Wäiss 2.5L", description: "Latexfaarf fir Maueren an Decken.", shortDesc: "Haut Deckkraaft" },
      "pt-BR": { name: "Tinta Parede Branco 2.5L", description: "Tinta látex para paredes e tetos. Cobertura de aproximadamente 25m².", shortDesc: "Alta cobertura, fácil aplicação" },
    },
  },
  {
    id: "prod-020",
    slug: "tupperware-set-5-pocos",
    sku: "ACT-KIT-002",
    ean: "5414315001020",
    price: 3.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 300,
    images: [{ url: "", alt: "Set Tupperware" }],
    attributes: [
      { name: "Pieces", value: "5" },
      { name: "Material", value: "Plástico BPA-free" },
    ],
    translations: {
      "pt-PT": { name: "Set Tupperware 5 Peças", description: "Conjunto de 5 recipientes herméticos de diferentes tamanhos. Livre de BPA. Micro-ondas seguro.", shortDesc: "Herméticos e práticos" },
      "fr-FR": { name: "Set Boîtes 5 Pièces", description: "Ensemble de 5 boîtes hermétiques de différentes tailles. Sans BPA. Compatible micro-ondes.", shortDesc: "Hermétiques et pratiques" },
      "es-ES": { name: "Set Tupperware 5 Piezas", description: "Juego de 5 recipientes herméticos de diferentes tamaños. Libre de BPA. Apto microondas.", shortDesc: "Herméticos y prácticos" },
      "it-IT": { name: "Set Contenitori 5 Pezzi", description: "Set di 5 contenitori ermetici di diverse dimensioni. Senza BPA. Adatti al microonde.", shortDesc: "Ermatici e pratici" },
      "nl-NL": { name: "Bewaarboxen Set 5 Stuks", description: "Set van 5 luchtdichte bewaarboxen in verschillende maten. BPA-vrij. Magnetronbestendig.", shortDesc: "Luchtdicht en praktisch" },
      "de-DE": { name: "Aufbewahrungsboxen Set 5 Teile", description: "Set mit 5 luftdichten Aufbewahrungsboxen in verschiedenen Größen. BPA-frei. Mikrowellengeeignet.", shortDesc: "Luftdicht und praktisch" },
      "fr-BE": { name: "Set Boîtes 5 Pièces", description: "Ensemble de 5 boîtes hermétiques. Sans BPA.", shortDesc: "Hermétiques et pratiques" },
      "lb-LU": { name: "Opsatursboxen Set 5 Stéck", description: "Set mat 5 luftdichten Opsatursboxen.", shortDesc: "Luftdicht a praktesch" },
      "pt-BR": { name: "Set Tupperware 5 Peças", description: "Conjunto de 5 recipientes herméticos de diferentes tamanhos.", shortDesc: "Herméticos e práticos" },
    },
  },
  {
    id: "prod-021",
    slug: "cobertor-microfibra-150x200",
    sku: "ACT-HOM-002",
    ean: "5414315001021",
    price: 8.99,
    originalPrice: 13.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 65,
    images: [{ url: "", alt: "Cobertor Microfibra" }],
    attributes: [
      { name: "Size", value: "150x200cm" },
      { name: "Material", value: "Microfibra 280g/m²" },
    ],
    translations: {
      "pt-PT": { name: "Cobertor Microfibra 150x200", description: "Cobertor ultra macio em microfibra premium. Ideal para todas as estações. Lavável à máquina.", shortDesc: "Macio como uma nuvem" },
      "fr-FR": { name: "Couverture Microfibre 150x200", description: "Couverture ultra douce en microfibre premium. Idéale pour toutes les saisons. Lavable en machine.", shortDesc: "Douce comme un nuage" },
      "es-ES": { name: "Manta Microfibra 150x200", description: "Manta ultra suave en microfibra premium. Ideal para todas las estaciones. Lavable a máquina.", shortDesc: "Suave como una nube" },
      "it-IT": { name: "Coperta Microfibra 150x200", description: "Coperta ultra morbida in microfibra premium. Ideale per tutte le stagioni. Lavabile in lavatrice.", shortDesc: "Morbida come una nuvola" },
      "nl-NL": { name: "Dekbed Microvezel 150x200", description: "Ultra zacht dekbed in premium microvezel. Ideaal voor alle seizoenen. Machinewasbaar.", shortDesc: "Zacht als een wolk" },
      "de-DE": { name: "Kuscheldecke Mikrofaser 150x200", description: "Ultra weiche Kuscheldecke aus Premium-Mikrofaser. Ideal für alle Jahreszeiten. Maschinenwaschbar.", shortDesc: "Weich wie eine Wolke" },
      "fr-BE": { name: "Couverture Microfibre 150x200", description: "Couverture ultra douce en microfibre premium.", shortDesc: "Douce comme un nuage" },
      "lb-LU": { name: "Kuscheldeck Mikrofaser 150x200", description: "Ultra waarm Kuscheldeck aus Premium Mikrofaser.", shortDesc: "Waarm wéi eng Wollek" },
      "pt-BR": { name: "Cobertor Microfibra 150x200", description: "Cobertor ultra macio em microfibra premium.", shortDesc: "Macio como uma nuvem" },
    },
  },
  {
    id: "prod-022",
    slug: "sapatilha-desporto-unissex",
    sku: "ACT-CLT-002",
    ean: "5414315001022",
    price: 7.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 140,
    images: [{ url: "", alt: "Sapatilha de Desporto" }],
    attributes: [
      { name: "Sizes", value: "36-45" },
      { name: "Material", value: "Malha/Rede" },
    ],
    translations: {
      "pt-PT": { name: "Sapatilha Desporto Unissex", description: "Sapatilha de desporto leve e respirável. Sola antiderrapante. Ideal para caminhadas.", shortDesc: "Leve e confortável" },
      "fr-FR": { name: "Baskets Sport Unisexe", description: "Baskets de sport légères et respirantes. Semelle antidérapante. Idéal pour la marche.", shortDesc: "Légère et confortable" },
      "es-ES": { name: "Zapatilla Deporte Unisex", description: "Zapatilla de deporte ligera y transpirable. Suela antideslizante. Ideal para caminar.", shortDesc: "Ligera y cómoda" },
      "it-IT": { name: "Scarpe Sportive Unisex", description: "Scarpe sportive leggere e traspiranti. Suola antiscivolo. Ideali per camminate.", shortDesc: "Leggere e comode" },
      "nl-NL": { name: "Sportschoenen Unisex", description: "Lichte en ademende sportschoenen. Antislip zool. Ideaal voor wandelen.", shortDesc: "Licht en comfortabel" },
      "de-DE": { name: "Sportschuhe Unisex", description: "Leichte und atmungsaktive Sportschuhe. Rutschfeste Sohle. Ideal zum Wandern.", shortDesc: "Leicht und bequem" },
      "fr-BE": { name: "Baskets Sport Unisexe", description: "Baskets de sport légères et respirantes.", shortDesc: "Légère et confortable" },
      "lb-LU": { name: "Sportschongen Unisex", description: "Liicht an odematend Sportschongen.", shortDesc: "Liicht a bequem" },
      "pt-BR": { name: "Tênis Esporte Unissex", description: "Tênis de esporte leve e respirável. Sola antiderrapante.", shortDesc: "Leve e confortável" },
    },
  },
  {
    id: "prod-023",
    slug: "chocolate-ao-leite-tablete-200g",
    sku: "ACT-FOO-003",
    ean: "5414315001023",
    price: 0.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 600,
    images: [{ url: "", alt: "Chocolate ao Leite" }],
    attributes: [
      { name: "Weight", value: "200g" },
      { name: "Type", value: "Chocolate ao Leite" },
    ],
    translations: {
      "pt-PT": { name: "Chocolate ao Leite 200g", description: "Tablete de chocolate ao leite cremoso. Cacau de qualidade. Perfeito para qualquer momento.", shortDesc: "Cremoso e irresistível" },
      "fr-FR": { name: "Chocolat au Lait 200g", description: "Tablette de chocolat au lait onctueux. Cacao de qualité. Parfait pour tout moment.", shortDesc: "Onctueux et irrésistible" },
      "es-ES": { name: "Chocolate con Leche 200g", description: "Tableta de chocolate con leche cremoso. Cacao de calidad. Perfecto para cualquier momento.", shortDesc: "Cremoso e irresistible" },
      "it-IT": { name: "Cioccolato al Latte 200g", description: "Tavoletta di cioccolato al latte cremoso. Cacao di qualità. Perfetto per ogni momento.", shortDesc: "Cremoso e irresistibile" },
      "nl-NL": { name: "Melkchocolade 200g", description: "Roomse melkchocoladereep. Kwaliteitscacao. Perfect voor elk moment.", shortDesc: "Romig en onweerstaanbaar" },
      "de-DE": { name: "Milchschokolade 200g", description: "Cremige Milchschokoladentafel. Qualitäts-Kakao. Perfekt für jeden Moment.", shortDesc: "Cremig und unwiderstehlich" },
      "fr-BE": { name: "Chocolat au Lait 200g", description: "Tablette de chocolat au lait onctueux.", shortDesc: "Onctueux et irrésistible" },
      "lb-LU": { name: "Mëllechschokolat 200g", description: "Cremeg Mëllechschokoladentafel.", shortDesc: "Cremeg a onwiiderstänneg" },
      "pt-BR": { name: "Chocolate ao Leite 200g", description: "Tablete de chocolate ao leite cremoso.", shortDesc: "Cremoso e irresistível" },
    },
  },
  {
    id: "prod-024",
    slug: "vaso-planta-ceramica-12cm",
    sku: "ACT-GAR-002",
    ean: "5414315001024",
    price: 2.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 220,
    images: [{ url: "", alt: "Vaso Cerâmica" }],
    attributes: [
      { name: "Diameter", value: "12cm" },
      { name: "Material", value: "Cerâmica com furo de drenagem" },
    ],
    translations: {
      "pt-PT": { name: "Vaso Cerâmica 12cm", description: "Vaso de cerâmica com furo de drenagem. Ideal para plantas de interior. Acabamento mate elegante.", shortDesc: "Elegante e funcional" },
      "fr-FR": { name: "Pot Céramique 12cm", description: "Pot en céramique avec trou de drainage. Idéal pour les plantes d'intérieur. Finition mate élégante.", shortDesc: "Élégant et fonctionnel" },
      "es-ES": { name: "Maceta Cerámica 12cm", description: "Maceta de cerámica con agujero de drenaje. Ideal para plantas de interior. Acabado mate elegante.", shortDesc: "Elegante y funcional" },
      "it-IT": { name: "Vaso Ceramica 12cm", description: "Vaso in ceramica con foro di drenaggio. Ideale per piante da interno. Finitura opaca elegante.", shortDesc: "Elegante e funzionale" },
      "nl-NL": { name: "Bloempot Keramiek 12cm", description: "Keramieken bloempot met drainagegat. Ideaal voor kamerplanten. Elegante matte afwerking.", shortDesc: "Elegant en functioneel" },
      "de-DE": { name: "Blumentopf Keramik 12cm", description: "Keramiktopf mit Abflussloch. Ideal für Zimmerpflanzen. Elegante matte Oberfläche.", shortDesc: "Elegant und funktional" },
      "fr-BE": { name: "Pot Céramique 12cm", description: "Pot en céramique avec trou de drainage.", shortDesc: "Élégant et fonctionnel" },
      "lb-LU": { name: "Blumepot Keramik 12cm", description: "Keramikblumepot mat Oflosslach.", shortDesc: "Elegant a funktional" },
      "pt-BR": { name: "Vaso Cerâmica 12cm", description: "Vaso de cerâmica com furo de drenagem.", shortDesc: "Elegante e funcional" },
    },
  },
];

export const MOCK_BANNERS = [
  {
    id: "banner-1",
    title: "Ofertas da Semana",
    subtitle: "Até 40% de desconto em milhares de produtos",
    image: "",
    gradient: "from-orange-500 via-orange-600 to-amber-500",
    ctaText: { "pt-PT": "Ver Ofertas", "fr-FR": "Voir les Offres", "es-ES": "Ver Ofertas", "it-IT": "Vedi Offerte", "nl-NL": "Bekijk Aanbiedingen", "de-DE": "Angebote sehen", "fr-BE": "Voir les Offres", "lb-LU": "Angeboter kucken", "pt-BR": "Ver Ofertas" },
    link: "weekly",
  },
  {
    id: "banner-2",
    title: "Entregas Grátis",
    subtitle: "Entregas ao domicílio grátis acima de 19,90€",
    image: "",
    gradient: "from-green-500 via-emerald-500 to-teal-500",
    ctaText: { "pt-PT": "Comprar Agora", "fr-FR": "Acheter Maintenant", "es-ES": "Comprar Ahora", "it-IT": "Acquista Ora", "nl-NL": "Nu Kopen", "de-DE": "Jetzt Kaufen", "fr-BE": "Acheter", "lb-LU": "Elooss kafen", "pt-BR": "Comprar Agora" },
    link: "home",
  },
  {
    id: "banner-3",
    title: "Novidades em Casa",
    subtitle: "Descubra a nova coleção de decoração e home",
    image: "",
    gradient: "from-blue-500 via-indigo-500 to-purple-500",
    ctaText: { "pt-PT": "Descobrir", "fr-FR": "Découvrir", "es-ES": "Descubrir", "it-IT": "Scoprire", "nl-NL": "Ontdekken", "de-DE": "Entdecken", "fr-BE": "Découvrir", "lb-LU": "Entdecken", "pt-BR": "Descobrir" },
    link: "category",
    linkSlug: "casa-decoracao",
  },
  {
    id: "banner-4",
    title: "Brinquedos & Lazer",
    subtitle: "Diversão para toda a família a preços incríveis",
    image: "",
    gradient: "from-pink-500 via-rose-500 to-red-500",
    ctaText: { "pt-PT": "Explorar", "fr-FR": "Explorer", "es-ES": "Explorar", "it-IT": "Esplorare", "nl-NL": "Verkennen", "de-DE": "Erkunden", "fr-BE": "Explorer", "lb-LU": "Erkunden", "pt-BR": "Explorar" },
    link: "category",
    linkSlug: "brinquedos-lazer",
  },
];

export const PRODUCT_CATEGORIES_MAP: Record<string, string[]> = {
  alimentacao: ["prod-001", "prod-016", "prod-023"],
  casa_decoracao: ["prod-004", "prod-011", "prod-012", "prod-014", "prod-018", "prod-020", "prod-021"],
  bricolage_ferramentas: ["prod-003", "prod-013", "prod-019"],
  jardim: ["prod-005", "prod-024"],
  animais: ["prod-006"],
  higiene_beleza: ["prod-002", "prod-007", "prod-015"],
  brinquedos_lazer: ["prod-009"],
  roupa_acessorios: ["prod-010", "prod-022"],
  papelaria_escritorio: ["prod-008", "prod-017"],
};
