import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    slug: "oleo-oliva-extra-virgem-750ml",
    sku: "ACT-FOO-001",
    ean: "5414315001001",
    price: 3.99,
    originalPrice: 5.49,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 150,
    images: [{ url: "/products/azeite.jpg", alt: "Azeite Extra Virgem" }],
    attributes: [
      { name: "Capacity", value: "750ml" },
      { name: "Origin", value: "Grécia" },
    ],
    translations: {
      "pt-PT": { name: "Azeite Extra Virgem 750ml", description: "Azeite de oliva extra virgem de alta qualidade, prensado a frio. Ideal para saladas e cozinhados.", shortDesc: "Azeite premium prensado a frio" },
      "fr-FR": { name: "Huile d'Olive Extra Vierge 750ml", description: "Huile d'olive extra vierge de haute qualidade, pressée à froid. Idéale pour les salades et la cuisine.", shortDesc: "Huile d'olive premium pressée à froid" },
      "es-ES": { name: "Aceite de Oliva Extra Virgen 750ml", description: "Aceite de oliva extra virgen de alta qualidade, prensado en frío. Ideal para ensaladas y cocinados.", shortDesc: "Aceite premium prensado en frío" },
      "it-IT": { name: "Olio Extra Vergine d'Oliva 750ml", description: "Olio extravergine di oliva di alta qualidade, spremuto a freddo. Ideale per insalate e cottura.", shortDesc: "Olio premium spremuto a freddo" },
      "nl-NL": { name: "Extra Vierge Olijfolie 750ml", description: "Extra vierge olijfolie van hoge qualidade, koudgeperst. Ideaal voor salades en koken.", shortDesc: "Premium koudgeperste olijfolie" },
      "de-DE": { name: "Natives Olivenöl Extra 750ml", description: "Hochwertiges natives Olivenöl Extra, kaltgepresst. Ideal für Salate und Kochen.", shortDesc: "Premium kaltgepresstes Olivenöl" },
      "fr-BE": { name: "Huile d'Olive Extra Vierge 750ml", description: "Huile d'olive extra vierge, pressée à froid.", shortDesc: "Huile premium pressée à froid" },
      "lb-LU": { name: "Extra Vierge Uelef 750ml", description: "Héchwäerteg extra Vierge Uelef, kalt gepresst.", shortDesc: "Premium kaltgepresst Uelef" },
      "pt-BR": { name: "Azeite de Oliva Extra Virgem 750ml", description: "Azeite de oliva extra virgem de alta qualidade, prensado a frio.", shortDesc: "Azeite premium prensado a frio" },
    },
  },
  {
    id: "prod-002",
    slug: "detergente-roupa-liquido-2l",
    sku: "ACT-CLE-001",
    ean: "5414315001002",
    price: 2.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: false,
    stockCount: 300,
    images: [{ url: "/products/detergente.jpg", alt: "Detergente Líquido" }],
    attributes: [
      { name: "Capacity", value: "2L" },
      { name: "Scent", value: "Lavanda" },
    ],
    translations: {
      "pt-PT": { name: "Detergente Líquido 2L", description: "Detergente líquido concentrado para roupa. Perfume suave de lavanda. Para 40 lavagens.", shortDesc: "Detergente concentrado, 40 lavagens" },
      "fr-FR": { name: "Lessive Liquide 2L", description: "Lessive liquide concentrée pour le linge. Parfum doux de lavande. Pour 40 lavages.", shortDesc: "Lessive concentrée, 40 lavages" },
      "es-ES": { name: "Detergente Líquido 2L", description: "Detergente líquido concentrado para la ropa. Suave aroma de lavanda. Para 40 lavados.", shortDesc: "Detergente concentrado, 40 lavados" },
      "it-IT": { name: "Detersivo Liquido 2L", description: "Detersivo liquido concentrato per bucato. Profumo delicato di lavanda. Per 40 lavaggi.", shortDesc: "Detersivo concentrato, 40 lavaggi" },
      "nl-NL": { name: "Vloeibaar Wasmiddel 2L", description: "Geconcentreerd vloeibaar wasmiddel. Zachte lavendelgeur. Voor 40 wasbeurten.", shortDesc: "Geconcentreerd wasmiddel, 40 wasbeurten" },
      "de-DE": { name: "Flüssigwaschmittel 2L", description: "Konzentriertes Flüssigwaschmittel. Sanfter Lavendelduft. Für 40 Wäschen.", shortDesc: "Konzentriertes Waschmittel, 40 Wäschen" },
      "fr-BE": { name: "Lessive Liquide 2L", description: "Lessive liquide concentrée pour le linge.", shortDesc: "Lessive concentrée" },
      "lb-LU": { name: "Flësseg Wäschmëttel 2L", description: "Konzentréiert flësseg Wäschmëttel. Milt Lavendelduft.", shortDesc: "Konzentréiert Wäschmëttel" },
      "pt-BR": { name: "Detergente Líquido 2L", description: "Detergente líquido concentrado para roupas. Aroma suave de lavanda.", shortDesc: "Detergente concentrado, 40 lavagens" },
    },
  },
  {
    id: "prod-003",
    slug: "kit-ferramentas-basico-45-pecas",
    sku: "ACT-BRI-001",
    ean: "5414315001003",
    price: 9.99,
    originalPrice: 14.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 75,
    images: [{ url: "/products/ferramentas.webp", alt: "Kit de Ferramentas" }],
    attributes: [
      { name: "Pieces", value: "45" },
      { name: "Material", value: "Aço Carbono" },
    ],
    translations: {
      "pt-PT": { name: "Kit Ferramentas 45 Peças", description: "Kit completo de ferramentas com 45 peças. Inclui chaves, martelo, alicate e mais.", shortDesc: "Kit completo para bricolage" },
      "fr-FR": { name: "Outil de Bricolage 45 Pièces", description: "Kit complet d'outils avec 45 pièces. Inclut clés, marteau, pince et plus.", shortDesc: "Kit complet para bricolage" },
      "es-ES": { name: "Kit de Herramientas 45 Piezas", description: "Kit completo de ferramentas con 45 piezas. Incluye llaves, martillo, alicate y más.", shortDesc: "Kit completo para bricolaje" },
      "it-IT": { name: "Kit Utensili 45 Pezzi", description: "Kit completo di utensili con 45 pezzi. Include chiavi, martello, pinza e altro.", shortDesc: "Kit completo per fai da te" },
      "nl-NL": { name: "Gereedschapskist 45 Stuks", description: "Complete gereedschapsset met 45 stuks. Inclusief sleutels, hamer, tang en meer.", shortDesc: "Complete klusset" },
      "de-DE": { name: "Werkzeugkasten 45 Teile", description: "Komplettes Werkzeugset mit 45 Teilen. Enthält Schlüssel, Hammer, Zange und mehr.", shortDesc: "Komplettes Werkzeugset" },
      "fr-BE": { name: "Kit Outils 45 Pièces", description: "Kit complet d'outils avec 45 pièces.", shortDesc: "Kit complet para bricolage" },
      "lb-LU": { name: "Geschirskasten 45 Stéck", description: "Kompletten Handwierkssatz mat 45 Stéck.", shortDesc: "Kompletten Handwierkssatz" },
      "pt-BR": { name: "Kit de Ferramentas 45 Peças", description: "Kit completo de ferramentas com 45 peças para bricolage.", shortDesc: "Kit completo para bricolage" },
    },
  },
  {
    id: "prod-004",
    slug: "conjunto-toalhas-banho-3-pocos",
    sku: "ACT-HOM-001",
    ean: "5414315001004",
    price: 7.99,
    originalPrice: 12.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 60,
    images: [{ url: "/products/toalhas.png", alt: "Conjunto de Toalhas" }],
    attributes: [
      { name: "Pieces", value: "3" },
      { name: "Material", value: "Algodão 100%" },
    ],
    translations: {
      "pt-PT": { name: "Conjunto Toalhas Banho 3 Peças", description: "Conjunto de toalhas de banho em algodão premium. Inclui 2 toalhas de rosto e 1 de banho.", shortDesc: "Toalhas de algodão premium" },
      "fr-FR": { name: "Ensemble Serviettes 3 Pièces", description: "Ensemble de serviettes de bain en coton premium. Inclus 2 serviettes de visage et 1 de bain.", shortDesc: "Serviettes en coton premium" },
      "es-ES": { name: "Juego de Toallas 3 Piezas", description: "Juego de toallas de baño en algodón premium. Incluye 2 toallas de rostro y 1 de baño.", shortDesc: "Toallas de algodón premium" },
      "it-IT": { name: "Set Asciugamani 3 Pezzi", description: "Set di asciugamani da bagno in cotone premium. Include 2 asciugamani viso e 1 da bagno.", shortDesc: "Asciugamani in cotone premium" },
      "nl-NL": { name: "Handdoekenset 3 Stuks", description: "Badhanddoekenset in premium katoen. Inclusief 2 washandjes en 1 badhanddoek.", shortDesc: "Premium katoenen handdoeken" },
      "de-DE": { name: "Handtuchset 3 Teile", description: "Badhandtuchset aus Premium-Baumwolle. Enthält 2 Waschlappen und 1 Badetuch.", shortDesc: "Premium Baumwollhandtücher" },
      "fr-BE": { name: "Ensemble Serviettes 3 Pièces", description: "Ensemble de serviettes de bain en coton premium.", shortDesc: "Serviettes en coton premium" },
      "lb-LU": { name: "Handuchenset 3 Stéck", description: "Badhanduchenset aus Premium-Bamwull.", shortDesc: "Premium Bamwullhandducher" },
      "pt-BR": { name: "Jogo de Toalhas 3 Peças", description: "Jogo de toalhas de banho em algodão premium.", shortDesc: "Toalhas de algodão premium" },
    },
  },
  {
    id: "prod-005",
    slug: "fertilizante-universal-5kg",
    sku: "ACT-GAR-001",
    ean: "5414315001005",
    price: 4.49,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 200,
    images: [{ url: "/products/fertilizante.jpg", alt: "Fertilizante" }],
    attributes: [
      { name: "Weight", value: "5kg" },
      { name: "Type", value: "Universal" },
    ],
    translations: {
      "pt-PT": { name: "Fertilizante Universal 5kg", description: "Fertilizante universal para todas as plantas. Fórmula equilibrada NPK para crescimento saudável.", shortDesc: "Para todas as plantas" },
      "fr-FR": { name: "Engrais Universel 5kg", description: "Engrais universel pour toutes les plantes. Formule équilibrée NPK pour une croissance saine.", shortDesc: "Pour toutes les plantes" },
      "es-ES": { name: "Fertilizante Universal 5kg", description: "Fertilizante universal para todas las plantas. Fórmula equilibrada NPK.", shortDesc: "Para todas las plantas" },
      "it-IT": { name: "Concime Universale 5kg", description: "Concime universale per tutte le piante. Formula bilanciata NPK.", shortDesc: "Per tutte le piante" },
      "nl-NL": { name: "Universele Meststof 5kg", description: "Universele meststof voor alle planten. Gebalanceerde NPK-formule.", shortDesc: "Voor alle planten" },
      "de-DE": { name: "Universaldünger 5kg", description: "Universaldünger für alle Pflanzen. Ausgewogene NPK-Formel.", shortDesc: "Für alle Pflanzen" },
      "fr-BE": { name: "Engrais Universel 5kg", description: "Engrais universel pour toutes les plantes.", shortDesc: "Pour todas as plantas" },
      "lb-LU": { name: "Universaldünger 5kg", description: "Universaldünger fir all Planzen.", shortDesc: "Fir all Planzen" },
      "pt-BR": { name: "Fertilizante Universal 5kg", description: "Fertilizante universal para todas as plantas.", shortDesc: "Para todas as plantas" },
    },
  },
  {
    id: "prod-006",
    slug: "racao-cao-adulto-3kg",
    sku: "ACT-PET-001",
    ean: "5414315001006",
    price: 6.99,
    originalPrice: 8.99,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
    stockCount: 120,
    images: [{ url: "/products/racao.jpg", alt: "Ração para Cães" }],
    attributes: [
      { name: "Weight", value: "3kg" },
      { name: "Animal", value: "Cão Adulto" },
    ],
    translations: {
      "pt-PT": { name: "Ração Cão Adulto 3kg", description: "Ração completa e equilibrada para cães adultos. Com frango e legumes.", shortDesc: "Ração premium para cães" },
      "fr-FR": { name: "Aliment Chien Adulte 3kg", description: "Aliment complet et équilibré pour chiens adultes. Avec poulet et legumes.", shortDesc: "Aliment premium pour chiens" },
      "es-ES": { name: "Comida Perro Adulto 3kg", description: "Comida completa y equilibrada para perros adultos. Con pollo y verduras.", shortDesc: "Comida premium para perros" },
      "it-IT": { name: "Cibo Cane Adulto 3kg", description: "Cibo completo e bilanciato per cani adulti. Con pollo e verdure.", shortDesc: "Cibo premium per cani" },
      "nl-NL": { name: "Hondenvoer Volwassen 3kg", description: "Compleet en uitgebalanceerd hondenvoer voor volwassen honden. Met kip en groenten.", shortDesc: "Premium hondenvoer" },
      "de-DE": { name: "Hundefutter Erwachsen 3kg", description: "Vollwertiges und ausgewogenes Hundefutter für erwachsene Hunde. Mit Huhn und Gemüse.", shortDesc: "Premium Hundefutter" },
      "fr-BE": { name: "Aliment Chien Adulte 3kg", description: "Aliment complet pour chiens adultes.", shortDesc: "Aliment premium pour chiens" },
      "lb-LU": { name: "Hondsfriessen Erwuessen 3kg", description: "Kompletten Hondsfriessen fir erwuessen Honden.", shortDesc: "Premium Hondsfriessen" },
      "pt-BR": { name: "Ração Cão Adulto 3kg", description: "Ração completa para cães adultos. Com frango e legumes.", shortDesc: "Ração premium para cães" },
    },
  },
  {
    id: "prod-007",
    slug: "shampoo-solido-argan-85g",
    sku: "ACT-HYG-001",
    ean: "5414315001007",
    price: 1.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: false,
    stockCount: 500,
    images: [{ url: "/products/shampoo.webp", alt: "Shampoo Sólido" }],
    attributes: [
      { name: "Weight", value: "85g" },
      { name: "Ingredient", value: "Óleo de Argan" },
    ],
    translations: {
      "pt-PT": { name: "Shampoo Sólido Argan 85g", description: "Shampoo sólido com óleo de argan. Zero plástico, 100% natural. Equivalente a 2 frascos.", shortDesc: "Shampoo zero plástico" },
      "fr-FR": { name: "Shampoo Solide Argan 85g", description: "Shampoo solide à l'huile d'argan. Zéro plastique, 100% naturel. Équivalent à 2 flacons.", shortDesc: "Shampoo zéro plastique" },
      "es-ES": { name: "Champú Sólido Argán 85g", description: "Champú sólido con aceite de argán. Cero plástico, 100% natural. Equivalente a 2 frascos.", shortDesc: "Champú cero plástico" },
      "it-IT": { name: "Shampoo Solido Argan 85g", description: "Shampoo solido con olio di argan. Zero plastica, 100% naturale. Equivalente a 2 flaconi.", shortDesc: "Shampoo zero plastica" },
      "nl-NL": { name: "Vast Shampoo Argan 85g", description: "Vast shampoo met arganolie. Zero plastic, 100% natuurlijk. Gelijk aan 2 flessen.", shortDesc: "Shampoo zero plastic" },
      "de-DE": { name: "Festshampoo Argan 85g", description: "Festshampoo mit Arganöl. Null Plastik, 100% natürlich. Entspricht 2 Flaschen.", shortDesc: "Shampoo null Plastik" },
      "fr-BE": { name: "Shampoo Solide Argan 85g", description: "Shampoo solide à l'huile d'argan. Zéro plastique.", shortDesc: "Shampoo zéro plastique" },
      "lb-LU": { name: "Festshampoo Argan 85g", description: "Festshampoo mat Arganuele. Null Plastik.", shortDesc: "Shampoo null Plastik" },
      "pt-BR": { name: "Shampoo Sólido Argan 85g", description: "Shampoo sólido com óleo de argan. Zero plástico, 100% natural.", shortDesc: "Shampoo zero plástico" },
    },
  },
  {
    id: "prod-008",
    slug: "kit-escolar-completo-12-pocos",
    sku: "ACT-OFF-001",
    ean: "5414315001008",
    price: 5.99,
    originalPrice: 8.99,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isOnSale: true,
    stockCount: 180,
    images: [{ url: "/products/kit-escolar.jpg", alt: "Kit Escolar" }],
    attributes: [
      { name: "Pieces", value: "12" },
      { name: "Type", value: "Material Escolar" },
    ],
    translations: {
      "pt-PT": { name: "Kit Escolar 12 Peças", description: "Kit escolar completo com canetas, lápis, borracha, régua e caderno. Tudo num estojo.", shortDesc: "Tudo para voltar às aulas" },
      "fr-FR": { name: "Kit Scolaire 12 Pièces", description: "Kit scolaire complet avec stylos, crayons, gomme, règle et cahier. Tout dans une trousse.", shortDesc: "Tout pour la rentrée" },
      "es-ES": { name: "Kit Escolar 12 Piezas", description: "Kit escolar completo con bolígrafos, lápices, goma, regla y cuaderno.", shortDesc: "Todo para la vuelta al cole" },
      "it-IT": { name: "Kit Scolastico 12 Pezzi", description: "Kit scolastico completo con penne, matite, gomma, righello e quaderno.", shortDesc: "Tutto per la scuola" },
      "nl-NL": { name: "Schoolset 12 Stuks", description: "Complete schoolset met pennen, potloden, gum, liniaal en schrift.", shortDesc: "Alles voor school" },
      "de-DE": { name: "Schulset 12 Teile", description: "Komplettes Schulset mit Stiften, Bleistiften, Radiergummi, Lineal und Heft.", shortDesc: "Alles für die Schule" },
      "fr-BE": { name: "Kit Scolaire 12 Pièces", description: "Kit scolaire complet.", shortDesc: "Tout pour la rentrée" },
      "lb-LU": { name: "Schoulset 12 Stéck", description: "Kompletten Schoulset.", shortDesc: "Alles fir d'Schoul" },
      "pt-BR": { name: "Kit Escolar 12 Peças", description: "Kit escolar completo com canetas, lápis e mais.", shortDesc: "Tudo para voltar às aulas" },
    },
  },
  {
    id: "prod-009",
    slug: "puzzle-1000-pocos-paisagem",
    sku: "ACT-TOY-001",
    ean: "5414315001009",
    price: 3.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: false,
    stockCount: 90,
    images: [{ url: "/products/puzzle.webp", alt: "Puzzle 1000 Peças" }],
    attributes: [
      { name: "Pieces", value: "1000" },
      { name: "Theme", value: "Paisagem" },
    ],
    translations: {
      "pt-PT": { name: "Puzzle 1000 Peças - Paisagem", description: "Puzzle de 1000 peças com paisagem europeia. Impressão de alta qualidade em cartão grosso.", shortDesc: "Puzzle para toda a família" },
      "fr-FR": { name: "Puzzle 1000 Pièces - Paysage", description: "Puzzle de 1000 pièces avec paysage européen. Impression haute qualidade sur carton épais.", shortDesc: "Puzzle pour toute la famille" },
      "es-ES": { name: "Puzzle 1000 Piezas - Paisaje", description: "Puzzle de 1000 piezas con paisaje europeo. Impresión de alta qualidade.", shortDesc: "Puzzle para toda la familia" },
      "it-IT": { name: "Puzzle 1000 Pezzi - Paesaggio", description: "Puzzle di 1000 pezzi con paesaggio europeo. Stampa di alta qualidade.", shortDesc: "Puzzle per tutta la famiglia" },
      "nl-NL": { name: "Puzzle 1000 Stuks - Landschap", description: "Puzzle van 1000 stuks met Europees landschap. Hoge qualidade druk op dik karton.", shortDesc: "Puzzle voor het hele gezin" },
      "de-DE": { name: "Puzzle 1000 Teile - Landschaft", description: "Puzzle mit 1000 Teilen, europäisches Landschaftsmotiv. Hochwertiger Druck auf starkem Karton.", shortDesc: "Puzzle für die ganze Familie" },
      "fr-BE": { name: "Puzzle 1000 Pièces - Paysage", description: "Puzzle de 1000 pièces avec paysage.", shortDesc: "Puzzle pour toute la famille" },
      "lb-LU": { name: "Puzzle 1000 Stéck - Landschaft", description: "Puzzle mat 1000 Stéck, europäescht Landschaftsmotiv.", shortDesc: "Puzzle fir déi ganz Famill" },
      "pt-BR": { name: "Quebra-cabeça 1000 Peças - Paisagem", description: "Quebra-cabeça de 1000 peças com paisagem europeia.", shortDesc: "Quebra-cabeça para toda a família" },
    },
  },
  {
    id: "prod-010",
    slug: "camisola-algodao-unissex",
    sku: "ACT-CLT-001",
    ean: "5414315001010",
    price: 4.99,
    originalPrice: 7.99,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: true,
    stockCount: 250,
    images: [{ url: "/products/camisola.jpg", alt: "Camisola de Algodão" }],
    attributes: [
      { name: "Material", value: "Algodão 100%" },
      { name: "Sizes", value: "S, M, L, XL, XXL" },
    ],
    translations: {
      "pt-PT": { name: "Camisola Algodão Unissex", description: "Camisola de algodão 100% confortável. Corte regular, ideal para o dia a dia.", shortDesc: "Confortável algodão premium" },
      "fr-FR": { name: "T-shirt Coton Unisexe", description: "T-shirt 100% coton confortable. Coupe régulière, idéal pour tous les jours.", shortDesc: "Coton premium confortable" },
      "es-ES": { name: "Camiseta Algodón Unisex", description: "Camiseta de algodón 100% cómoda. Corte regular, ideal para el día a día.", shortDesc: "Algodón premium cómodo" },
      "it-IT": { name: "T-shirt Cotone Unisex", description: "T-shirt 100% cotone confortevole. Taglio regolare, ideale per tutti i giorni.", shortDesc: "Cotone premium confortevole" },
      "nl-NL": { name: "T-shirt Katoen Unisex", description: "Comfortabel T-shirt 100% katoen. Reguliere pasvorm, ideaal voor alledag.", shortDesc: "Premium katoen comfortabel" },
      "de-DE": { name: "Baumwoll-T-Shirt Unisex", description: "Bequemes 100% Baumwoll-T-Shirt. Reguläre Passform, ideal für jeden Tag.", shortDesc: "Premium Baumwolle bequem" },
      "fr-BE": { name: "T-shirt Coton Unisexe", description: "T-shirt 100% coton confortable.", shortDesc: "Coton premium confortable" },
      "lb-LU": { name: "Bamwoll T-Shirt Unisex", description: "Bequemt 100% Bamwoll T-Shirt.", shortDesc: "Premium Bamwoll bequem" },
      "pt-BR": { name: "Camiseta Algodão Unissex", description: "Camiseta de algodão 100% confortável.", shortDesc: "Algodão premium confortável" },
    },
  },
  {
    id: "prod-011",
    slug: "velas-aromaticas-set-6",
    sku: "ACT-DEC-001",
    ean: "5414315001011",
    price: 2.99,
    originalPrice: undefined,
    isActive: true,
    isFeatured: true,
    isNew: true,
    isOnSale: false,
    stockCount: 350,
    images: [{ url: "/products/velas.jpg", alt: "Velas Aromáticas" }],
    attributes: [
      { name: "Pieces", value: "6" },
      { name: "Burn Time", value: "4h cada" },
    ],
    translations: {
      "pt-PT": { name: "Velas Aromáticas Set 6", description: "Conjunto de 6 velas aromáticas com aromas de lavanda, baunilha e cítricos. Tempo de queima: 4h cada.", shortDesc: "Ambiente acolhedor" },
      "fr-FR": { name: "Bougies Parfumées Set 6", description: "Ensemble de 6 bougies parfumées aux arômes de lavande, vanille et agrumes. Temps de combustion: 4h chacune.", shortDesc: "Ambiance chaleureuse" },
      "es-ES": { name: "Velas Aromáticas Set 6", description: "Juego de 6 velas aromáticas con aromas de lavanda, vainilla y cítricos. Tiempo de combustión: 4h cada.", shortDesc: "Ambiente acogedor" },
      "it-IT": { name: "Candele Profumate Set 6", description: "Set di 6 candele profumate con aromi di lavanda, vaniglia e agrumi. Tempo di combustione: 4h ciascuna.", shortDesc: "Atmosfera accogliente" },
      "nl-NL": { name: "Geurkaarsen Set 6", description: "Set van 6 geurkaarsen met lavendel-, vanille- en citroenaroma's. Brandtijd: 4 uur per kaars.", shortDesc: "Gezellige sfeer" },
      "de-DE": { name: "Duftkerzen Set 6", description: "Set mit 6 Duftkerzen in Lavendel-, Vanille- und Zitrusdüften. Brenndauer: 4h pro Kerze.", shortDesc: "Gemütliche Atmosphäre" },
      "fr-BE": { name: "Bougies Parfumées Set 6", description: "Ensemble de 6 bougies parfumées.", shortDesc: "Ambiance chaleureuse" },
      "lb-LU": { name: "Duftrausen Set 6", description: "Set mat 6 Duftrausen.", shortDesc: "Gemittlech Atmosphär" },
      "pt-BR": { name: "Velas Aromáticas Set 6", description: "Conjunto de 6 velas aromáticas.", shortDesc: "Ambiente acolhedor" },
    },
  },
  {
    id: "prod-012",
    slug: "conjunto-talheres-24-pocos",
    sku: "ACT-KIT-001",
    ean: "5414315001012",
    price: 8.99,
    originalPrice: 12.49,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isOnSale: true,
    stockCount: 80,
    images: [{ url: "/products/talheres.webp", alt: "Conjunto de Talheres" }],
    attributes: [
      { name: "Pieces", value: "24" },
      { name: "Material", value: "Aço Inoxidável" },
    ],
    translations: {
      "pt-PT": { name: "Conjunto Talheres 24 Peças", description: "Faqueiro completo de 24 peças em aço inoxidável. Inclui facas, garfos, colheres de sopa e de chá.", shortDesc: "Aço inox de alta qualidade" },
      "fr-FR": { name: "Ménagère 24 Pièces", description: "Ménagère complète de 24 pièces en acier inoxydable. Inclut couteaux, fourchettes, cuillères à soupe et à café.", shortDesc: "Acier inox haute qualidade" },
      "es-ES": { name: "Juego de Cubiertos 24 Piezas", description: "Juego de cubiertos completo de 24 piezas en acero inoxidable.", shortDesc: "Acero inox de alta qualidade" },
      "it-IT": { name: "Set Posate 24 Pezzi", description: "Set di posate completo da 24 pezzi em acciaio inossidabile.", shortDesc: "Acciaio inox di alta qualidade" },
      "nl-NL": { name: "Bestekset 24 Stuks", description: "Complete 24-delige bestekset van roestvrij staal.", shortDesc: "Hoogwaardig RVS" },
      "de-DE": { name: "Besteckset 24 Teile", description: "Komplettes 24-teiliges Besteckset aus Edelstahl.", shortDesc: "Hochwertiger Edelstahl" },
      "fr-BE": { name: "Ménagère 24 Pièces", description: "Ménagère complète de 24 pièces em acier inoxydable.", shortDesc: "Acier inox haute qualidade" },
      "lb-LU": { name: "Besteckset 24 Stéck", description: "Komplett 24-stéckeg Besteckset aus Edelstahl.", shortDesc: "Héichwäertegen Edelstahl" },
      "pt-BR": { name: "Jogo de Talheres 24 Peças", description: "Jogo de talheres completo de 24 peças em aço inoxidável.", shortDesc: "Aço inox de alta qualidade" },
    },
  },
];
